### ISSUE TITLE
Application crashing .. not starting after successful deployment

### ISSUE THREAD

**Issue by MangeshPatankar** [IBM/watson-banking-chatbot#39]
All services are provisioned. But application is crashing continuously

**Comment by sauravraiguru** [comment]
@MangeshPatankar The app deployment will fail if you already have a discovery service instance, because of the org limit of 1 discovery service. Pls check n let us know.
FYI. It was deployed this weekend for 100+ participants.

**Comment by MangeshPatankar** [comment]
@sauravraiguru Ideally your script written should take care of that.....because people might have instances running

**Comment by sauravraiguru** [comment]
@MangeshPatankar We can create many discovery lite services in the free trial period, but can have only 1 custom collection at an org level. 
Since you already have one that is causing issue to create another one. 
- Either we can set it the DISCOVERY_ENVIRONMENT_ID to an existing collection or delete existing one.
- Other approach using a standard (paid) service. Both are having their own hassles.

**Comment by sauravraiguru** [comment]
Closing this issue as issue #20 exists with same reason.
