### ISSUE TITLE
Conversation is responding instead of Discovery

### ISSUE THREAD

**Issue by pdcruz48374** [IBM/watson-banking-chatbot#45]
I am finding it hard for the Chatbot to answer any Discovery Questions from the docs. Ant tips?

See examples below - it is using the Conversation answers based in Confidence level even though I am typing in questions straight from the docs

It is picking up the Conversation intent and responding

[Demo Github Issues.docx](https://github.com/IBM/watson-banking-chatbot/files/1411813/Demo.Github.Issues.docx)

**Comment by markstur** [comment]
I just saw the details in the .docx file.  Turns out this was because after the "which payment" prompt it is expecting a reply like "electricity bill" or "mobile bill".  That is why it did not go to discovery.

There were other cases where the conversation used intents and had dialog to reply. This has been fixed (or at least improved -- perhaps ongoing). That was not the issue in this example.
